# The URL the site will be built for
base_url = "https://presheaf.dev"
title = "mug's blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "terminimal"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "tags"},
]

default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "one-dark"

[extra]
# Put all your custom variables here

accent_color = "pink"
background_color = "blue"

logo_text = "mug's blog"

author = "Luiz Mugnaini"

# $BASE_URL is going to be substituted by base_url from configuration
menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "about", url = "$BASE_URL/about"},
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "code", url = "https://git.sr.ht/~presheaf", newtab = true},
    {name = "misc", url = "$BASE_URL/misc"},
]

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

post_view_navigation_prompt = "Read more"

use_full_hack_font = true

favicon = "/favicon_knot-192x192.png"
favicon_mimetype = "image/png"

# Optional: Set how <title> elements are rendered.
# Values:
# - "main_only" -- only the main title (`config.title`) is rendered.
# - "page_only" -- only the page title (if defined) is rendered,
#                  falling back to `config.title` if not defined or empty.
# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
#
# Note that the main (index) page only has the main title.
page_titles = "main_only"
